### ISSUE TITLE
add "allow deselect on Single Selects"

### ISSUE THREAD

**Issue by Andrey1906** [silviomoreto/bootstrap-select#1575] opened 2016-12-03 16:16 UTC
Hellow , Tell me please how to add an option like on the picture. button "x" to refresh select.
![example](https://cloud.githubusercontent.com/assets/20841298/20860604/f7a54382-b98c-11e6-8141-b6e516ed70a9.jpg)

**Comment by amitsquare** [comment] 2016-12-08 18:17
1449 , Same issue which was opened by me .
But still not a concrete solution for this .

**Comment by caseyjhol** [comment] 2016-12-08 19:29
Duplicate of #1449.

**Closed by caseyjhol** 2016-12-08 19:29 UTC
