### ISSUE TITLE
SCRIPT16389: Unspecified error.

### ISSUE THREAD

**Issue by anyway111** [silviomoreto/bootstrap-select#963] opened 2015-03-12 06:48 UTC
When i add 'data-live-search-placeholder' atrribute <br>
IE11 on windows 8.1 has freezed and show message on debug mode as bellow<br>
SCRIPT16389: Unspecified error.

**Comment by caseyjhol** [comment] 2015-05-08 16:16
Duplicate of #851.

**Closed by caseyjhol** 2015-05-08 16:16 UTC
