### ISSUE TITLE
$el.selectpicker('val',value) causes errors e.stopPropagation is not a function

### ISSUE THREAD

**Issue by fusionbeam** [silviomoreto/bootstrap-select#1366] opened 2016-04-15 15:29 UTC
bootstrap-select 1.10.0
jquery 2.2.3

---

anyone encountering the same issue?

**Comment by arambadk** [comment] 2016-04-17 19:44
Same here

**Comment by caseyjhol** [comment] 2016-04-18 14:11
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.

**Comment by kovart** [comment] 2016-04-20 17:57
I had the same issue, but it solved after I call refresh function before changing
`$(element).selectpicker('refresh');
 $(element).selectpicker('val', 1);`

**Comment by maximelebreton** [comment] 2016-05-20 14:14
+1

**Comment by PhilPJL** [comment] 2016-11-18 17:31
I have this issue also
![snip](https://cloud.githubusercontent.com/assets/271656/20439566/033576a2-adb4-11e6-889d-ff9926a8e15b.PNG)

Using jQuery 1.12.4 and bootstrap-select 1.11.2 on IE 11 or IE Edge
 
                        picker.selectpicker('val', init);

fails, 

but
                        picker.val(init);
                        picker.selectpicker('refresh');

succeeds.

If I update jQuery to 3.1.1 then either way succeeds.

**Comment by caseyjhol** [comment] 2016-11-21 04:21
Closing this until somebody can follow [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

**Comment by PhilPJL** [comment] 2016-11-22 17:15
Ok, here's my first attempt at using jsBin  [https://jsbin.com/muvuguy/347/edit?html,js,output](url)
The issue only appears in $(document).ready and when using jquery < V2.

In the demo uncheck 'auto-run with JS'.
Click 'run with JS'.  The select picker is initialised.
Now comment out the jquery-3.1.1 script block and uncomment the jquery-1.12.4 block. 
Click 'run with JS'.  The select picker is **not** initialised.
However, using either of the 'test' buttons does initialise the picker for either version of jquery.

**Comment by caseyjhol** [comment] 2016-11-22 18:08
The reason this works with jQuery 3.0.0 and above is `$(document).ready()` is now fired asynchronously. Because of the test page's small size, `$(window).on('load')` is fired _before_ `$(document).ready()`, which allows bootstrap-select to initiate first, before setting the value in `$(document).ready()`. We run into this issue (attempting to set the value of the select before it's even initialized) in situations where it takes longer to load the page, or with any version of jQuery prior to 3.0.0. A workaround in the meantime is to use `$(window).on('load')` instead of `$(document).ready()`.

**Comment by caseyjhol** [comment] 2016-11-22 18:29
Duplicate of #1167.

**Closed by caseyjhol** 2016-11-22 18:29 UTC
