### ISSUE TITLE
HTML5 validation error placement Error

### ISSUE THREAD

**Issue by saikiranmarripati** [silviomoreto/bootstrap-select#1169] opened 2015-10-05 13:56 UTC
I am unable to place the HTML5 validation message on exact position on my select tag

**Comment by rajatsaxena035** [comment] 2015-10-23 06:18
"required" validation message is not coming at right position.

**Comment by caseyjhol** [comment] 2015-10-23 17:32
Duplicate of #514.

**Closed by caseyjhol** 2015-10-23 17:32 UTC
