### ISSUE TITLE
data-content option shows code on option hover

### ISSUE THREAD

**Issue by emage** [silviomoreto/bootstrap-select#896] opened 2015-01-28 20:41 UTC
If i am using the data-content option and if the mouse pointer is over the selected item it shows the jibberish code in the tooltip-like bubble

How can i disabled this option to show content in this tooltip

**Comment by Khrysller** [comment] 2015-01-28 23:54
I am facing the same thing

**Comment by jgambarios** [comment] 2015-01-29 13:46
Same here, related to #469 it seems it won't be fix it soon....

**Comment by caseyjhol** [comment] 2015-04-30 22:18
Duplicate of #469.

**Closed by caseyjhol** 2015-04-30 22:18 UTC
