### ISSUE TITLE
Setting `val` doesn't work

### ISSUE THREAD

**Issue by shaneparsons** [silviomoreto/bootstrap-select#1167] opened 2015-10-02 21:09 UTC
Using the following `$('.selectpicker').selectpicker('val', '1');` to preset the value of my select is returning the following error.

`Uncaught TypeError: e.stopPropagation is not a function`

The error is pointing to line 258 in bootstrap-select.js if it helps.
i.e.

```
if (e) {
    e.stopPropagation();
    e.preventDefault();
}
```

**Comment by frutality** [comment] 2015-10-14 06:03
+1
I see this error too.

**Comment by frutality** [comment] 2015-10-14 06:39
I am sorry I hurry. I see very strange thing. If I do this
`<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.7.3/js/bootstrap-select.min.js"></script>`
at my page, all works fine. There is no errors in browser console and `$('.selectpicker').selectpicker('val', '1')` works.

But If I save this file from CDN to my project directory and do this `<script src="/media/libs/bootstrap-select.min.js"></script>`
then I see error `d.stopPropagation is not a function`. And `selectpicker('val')` doesn't work.

**Comment by frutality** [comment] 2015-10-14 11:08
Well.. I'm confused. In Firefox, if I open page first time: no errors. All works as expected. But if I refresh page, I see error.

In Chrome all works fine. 

Problem is, I can't reproduce it on jsfiddle.

**Comment by frutality** [comment] 2015-10-14 12:45
Finally I found what was the probmle. It's not the browser and not the library error. 
Problem was in appending `options` to `<select></select>`. If you are not refreshing selectpicker, then maybe you'll see the error. Or maybe not. 

I've created fiddle: http://jsfiddle.net/nwd6gm6n/6/ but if you'll try to reproduce this situation, just copy source from fiddle to local html-file. Don't know why, but I can't get an error with jsfiddle.

**Comment by dougdoug** [comment] 2015-12-02 13:37
Replace the conventional code:

     $target.selectpicker("val", value);

For this:

     $target.val(value);
     $target.selectpicker("refresh");

**Comment by goyatparmod** [comment] 2015-12-23 00:44
I have same issue seems .val() not working for me as well.I am using ng-repeat in HTML and i tried following options nothing works. Appreciate any help.

$('#state-search').selectpicker('selectAll');
$state-search.selectpicker("val",$scope.states[0]);
$('#state-search').selectpicker("val",'Utah');
 $('#state-search').selectpicker('refresh');

**Comment by maximelebreton** [comment] 2016-05-09 12:54
+1

**Comment by caseyjhol** [comment] 2016-05-09 17:10
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.

**Comment by karthiksrinivasan** [comment] 2016-08-08 17:59
I tried the following and it works.

```
 $target.selectpicker("refresh");
 $target.val(value);
 $target.selectpicker("refresh");
```
@D-Skywalker 's suggestion did not work for me, and I built on that to include additional refresh.

I believe there is some sort of delay induced by  `$target.selectpicker("refresh");` which is causing this issue.

**Comment by caseyjhol** [comment] 2016-08-08 19:00
Can somebody _please_ provide an example of this feature not working? I would love to get this figured out.

**Comment by maximelebreton** [comment] 2016-08-09 09:35
Same `Uncaught TypeError: e.stopPropagation is not a function` problem, and fixed with a 0 delay timer:

```
var val = $this.val();
setTimeout(function(){
  $this.selectpicker('val', val);
  if (val) {
    $this.trigger("change");
  }
 }, 0);
```

Dont have time to introspect, but I think this error came when the `val` function is called twice at the same time.
In my case, I use [jquery-phoenix](https://github.com/kugaevsky/jquery-phoenix) to save form state, and the bug came when I set the saved select state with `val` function on page initialisation.

**Comment by Jeremboo** [comment] 2016-09-28 08:55
+1

**Comment by caseyjhol** [comment] 2016-10-07 15:50
Instead of posting "+1", please provide an example. Here's a link to a bootstrap-select playground: http://silviomoreto.github.io/bootstrap-select/playground/.

**Closed** 2016-11-22 18:38 UTC

**Comment by yokidara01** [comment] 2017-05-12 16:20
same probleme tried all solutions above 
`  var agents = $(".selectpicker");
                    $(agents).each(function(key, val) {
                        if(arrayOfArrayOfvalues[key].length>1){
                         //   $(val).selectpicker('val',arrayOfArrayOfvalues[key])
                            $(val).selectpicker("refresh");
                            $(val).val(arrayOfArrayOfvalues[key]);
                            $(val).selectpicker("refresh");
                          //  $(val).selectpicker("refresh");
                            console.log("id of select :" + $(val).attr("id")+" values to put "+arrayOfArrayOfvalues[key])
                        }

                    });`

**Comment by D-Skywalker** [comment] 2017-05-12 17:16
@yokidara01 This code is realy confused, there are many things out from scope like arrayOfArrayOfvalues. I sugest you try use one of codes showed here in isolation before run your complete code.

**Comment by TheGP** [comment] 2017-08-07 14:58
example:

`                                $('select[name=event_id]').prepend($('<option>', {
                                    value: response.description.id,
                                    text: response.description.name
                                })).selectpicker('refresh').selectpicker('val', response.description.id);`

**Comment by josyfg** [comment] 2018-01-04 20:27
After weeks with the same error I change the bootstrap-select.js file in my local server and selectpicker works.
I found the new file in this link https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/js/bootstrap-select.min.js
