### ISSUE TITLE
Dropdown does not select if within Bootstrap Popover

### ISSUE THREAD

**Issue by davidenco** [silviomoreto/bootstrap-select#1466] opened 2016-08-13 10:20 UTC
I have 2 <select> components within a popover. When the popover opens, I can click into the dropdowns but upon clicking an option, the selection does not change.

Please see this jsfiddle:

https://jsfiddle.net/davidenco/uf6oohsu/

**Comment by caseyjhol** [comment] 2016-08-16 19:58
Duplicate of #383.

**Closed by caseyjhol** 2016-08-16 19:58 UTC
