### ISSUE TITLE
data-size and data-actions-box bug

### ISSUE THREAD

**Issue by erkanakoglu** [silviomoreto/bootstrap-select#1081] opened 2015-06-29 20:25 UTC
Hello,

İf i use data-size attirubute bigger than options count and  data-actions-box set true the action bottuns dont work.

**Comment by DrewBe121212** [comment] 2015-06-29 21:06
Hey erkanakoglu,

This is a duplicate of 1077 (just closed!!). Please see the commit for the fix there.

**Closed** 2015-06-29 21:30 UTC
