### ISSUE TITLE
Select box doesn't inherit Bootstrap rounded corners

### ISSUE THREAD

**Issue by xKairu** [silviomoreto/bootstrap-select#937] opened 2015-02-22 04:54 UTC
My code is here: https://github.com/xKairu/CoD-eSports-VODs/blob/master/templates/index.html#L8
Screenshot: http://i.imgur.com/Fd9mE4R.png

As you can see, the corners aren't rounded, unlike every other input element in Bootstrap.
I'm currently using 1.6.4. 1.6.3 had the right hand corners rounded, but they didn't link together like elements in input groups should.

**Comment by caseyjhol** [comment] 2015-02-24 01:14
This is caused by #756, where `.form-control` was permanently added to the button. This causes other issues as well, and will be fixed in an update.

**Closed** 2015-02-24 07:04 UTC
