### ISSUE TITLE
not sending in post form request

### ISSUE THREAD

**Issue by carlituxman** [silviomoreto/bootstrap-select#1541] opened 2016-10-25 09:54 UTC
In Laravel 5.3 I have a form, with multiple select without problems. But when I use bootstrap-select for the select multiple field, then it not arrives in the request input of the post.

Only occurs when the form is inside a table

**Comment by caseyjhol** [comment] 2016-10-25 20:13
Duplicate of #1342.

**Closed by caseyjhol** 2016-10-25 20:13 UTC
