### ISSUE TITLE
.selectpicker("val", "xxx") not work in ie9

### ISSUE THREAD

**Issue by whogy** [silviomoreto/bootstrap-select#775] opened 2014-10-29 08:30 UTC
hi, all

i try to set a default value via code ' selectpicker('val'. 'xxx')', and it works in FF and Chrome, but not work in IE9

**Comment by molaughlen** [comment] 2015-01-05 17:21
I'm able to repro this issue in IE11 as well, however reproducing it involves require.js and uglify.  In my environment, I observed the 'option' parameter in the Plugin function resolving to the event argument after the arguments are shifted.  Seems similar to #715 in spirit.  

If the function is updated to avoid redefining the option variable (e.g. use _option), then it works as expected.

**Comment by lazlolazarous** [comment] 2015-01-15 19:46
The problem is nearly identical to https://github.com/silviomoreto/bootstrap-select/issues/715, but that only fixed some behaviors.
Behaviors like _val()_ and _setStyle()_ are still broken, but the suggestion by @molaughlen does work.
I made a similar suggestion in my comment on that ticket (which was already closed, my bad).

**Closed** 2015-01-19 15:34 UTC
Labels: bug
