### ISSUE TITLE
When Bootstrap 4 support?

### ISSUE THREAD

**Issue by andreyugit** [silviomoreto/bootstrap-select#1320] opened 2016-03-06 02:15 UTC
When Bootstrap 4 support?

**Comment by saucysalamandar** [comment] 2016-03-07 03:09
Bootstrap 4 is in Alpha stage, meaning it has to reach the stage of stable release so that the author can script the library for Bootstrap 4.

**Comment by caseyjhol** [comment] 2016-03-07 17:46
Duplicate of #1135. Thanks @saucysalamandar.

**Closed by caseyjhol** 2016-03-07 17:46 UTC

**Comment by caseyjhol** [comment] 2018-04-19 15:42
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
