### ISSUE TITLE
data-live-search-placeholder does not work with Internet Explorer

### ISSUE THREAD

**Issue by gwenael-louandre** [silviomoreto/bootstrap-select#851] opened 2015-01-08 11:04 UTC
Hello,

I tried the new version (1.6.3) with Internet Explorer 10 and I have a big problem : the browser completely freezes and I have to restart it.

This example (http://jsfiddle.net/bx1jjkd0/) works with the 1.6.2 but if you put the last version (the real one because le cdnjs link is the 1.6.2) IE freezes.

My IE version is 10.0.9200.17183.

**Comment by OOPMan** [comment] 2015-02-10 09:26
This issue also affects IE11

**Comment by OOPMan** [comment] 2015-02-12 08:59
I have perofmed a git bisect between 1.6.2 and 1.6.3 and determined that 3c6c9684d6d964f2254978b74666c77f12c46f24 is the commit that introduced this issue. I'm going to drill down some more and try to see what the exact cause is.

**Comment by OOPMan** [comment] 2015-02-12 09:06
How bizarre, just a bunch of renames...

**Comment by OOPMan** [comment] 2015-02-12 09:11
But it's definitely the cause of IE freezing up. Switched to the commit before (fcf87bef99875bb8679afd4a45df53e0c71d8041) and it works fine. Switch to 3c6c9684d6d964f2254978b74666c77f12c46f24 and IE freezes.

**Comment by OOPMan** [comment] 2015-02-12 09:23
I am submitting this as a bug to the IE team because I'm quite sure this is a bug with IE.

**Comment by OOPMan** [comment] 2015-02-12 14:02
Hmmmmmm, I did some more digging and it seems the issue is actually related to usage of the placeholder functionality on the live-search input.

**Comment by anyway111** [comment] 2015-03-12 06:14
i have same issues, when i use  'data-live-search'  and  'data-live-search-placeholder' <br>
IE11 on windows 8.1 that freezes 
I have to restart IE :(<br>
please fix it quick

**Comment by OOPMan** [comment] 2015-03-12 08:14
The issue lies with IE10 and IE11. Do not use placeholder with live search.

**Comment by NomidUnmus** [comment] 2015-08-26 15:20
Found the bug in IE11: I was playing around with the developer tools and found a loop caused by lines 1231 `$(this).focus()`  and 1581 `e.stopPropagation()`:

    // SELECTPICKER NO CONFLICT
    // ========================

    // ...
    
    $(document)
    	.data('keycount', 0)
    	.on('keydown', '.bootstrap-select [data-toggle=dropdown], .bootstrap-select [role="menu"], .bs-searchbox input', Selectpicker.prototype.keydown)
    	.on('focusin.modal', '.bootstrap-select [data-toggle=dropdown], .bootstrap-select [role="menu"], .bs-searchbox input', function (e) {
    	e.stopPropagation(); // <---- here
    	});
and
    this.$searchbox.on('input propertychange', function () {
        // ...
        $(this).focus(); // <--- here
    }

Just comment `$(this).focus()` and the browser won't freeze anymore.

But clearly the live search won't work.

**Comment by tejender-phogat** [comment] 2016-04-04 06:11
Hi All, 

Any fix available for this issue, or still existing ?

Thanks

**Comment by OOPMan** [comment] 2016-04-04 07:07
@tejender-phogat Upgrade to a newer IE or dont use the live search placeholder feature.

**Comment by sraleci** [comment] 2017-07-06 19:57
I was running into this issue on 1.7.2 and it was fixed when I upgraded to the latest (1.12.2). With some investigation this issue might be able to be closed.

**Comment by caseyjhol** [comment] 2017-07-06 22:28
Marking this as closed unless somebody can provide an example of it still being an issue.

**Closed by caseyjhol** 2017-07-06 22:28 UTC
Labels: bug
