### ISSUE TITLE
SelectAll / DeselectAll not working

### ISSUE THREAD

**Issue by samighawi** [silviomoreto/bootstrap-select#820] opened 2014-12-01 16:52 UTC
Hello,

I am trying to run select all or deselect all programmatically but it is not working. I tried to debug the problem and found out that filtering :visible is removing all the objects that I have. Therefore, it always tries to click 0 objects.

this.$lis.not('.divider').not('.disabled').not('.selected').filter(':visible').find('a').click();

When I removed filter(':visible'), it worked. Any reason why this filter is causing the problem in my case?

Thanks in advance,
Sami

**Comment by t0xicCode** [comment] 2015-01-19 19:21
Mind creating a jsfiddle? I am unable to replicate the issue in my limited testing.

**Comment by petr-inmite** [comment] 2015-02-02 00:40
Probably a duplicate of #721 - the `:visible` selector prevents "programatic clicks" when the select is not opened, since the items are ... not visible...

@samighawi Could you please verify if #721 is the same issue?

**Comment by samighawi** [comment] 2015-02-02 11:15
Sorry for the late reply as I am swamped with work. Yes, I can verify that it is the same issue. Thank you for that. I have tried the solution in #721 and it works. I will try creating a JSFiddle soon if possible but at least the proposed solution is working.
Maybe a reason why it happens: I manipulate the list programmatically and add more items or remove them depending on the filter the user checks using AJAX. My additions might be the cause of the problem since the :visible selector is not at those items.

**Closed** 2015-02-02 11:15 UTC

**Comment by petr-inmite** [comment] 2015-02-02 12:00
@samighawi Thank you for verifying.
