### ISSUE TITLE
form validation not working right ( required='' )

### ISSUE THREAD

**Issue by Kryptonit3** [silviomoreto/bootstrap-select#1086] opened 2015-07-04 17:31 UTC
I have the drop-down select set as required
```
<select class="selectpicker bs-select-hidden" required multiple name="versions">
    <option value="1">4.2</option>
    <option value="2">5.0</option>
    <option value="3">5.1</option>
</select>
```

Everything works wonderfully unless..

A user hasn't made a selection but goes to submit the form. Normally the screen would jump to the select and highlight it, but since the `<select>` is hidden this is not the case.

`An invalid form control with name='versions' is not focusable.`

Is there a way to check for the `required` tag on the original `<select>` and listen for form submit and if no selection, jump to or `FLASH` the drop-down?

Thanks!

**Comment by caseyjhol** [comment] 2015-07-06 22:03
Duplicate of #514

**Closed by caseyjhol** 2015-07-06 22:03 UTC

**Comment by RaviDavda** [comment] 2015-08-18 10:56
I face same issue. I m using bootstrap selectpicker select box. At the time of submitting the form even if i  doesnt selected any value from selectbox it does not display any error even it is set to required. Please I am looking for solutions.

Thanks in advance
