### ISSUE TITLE
Using with Laravel: Data not submitted

### ISSUE THREAD

**Issue by Scarwolf** [silviomoreto/bootstrap-select#1528] opened 2016-10-03 10:03 UTC
Hello,

I'm using your library with the laravel form facade like this:

`{!! Form::select('user', $users, null, array('class' => 'selectpicker show-tick', 'data-live-search' => 'true', 'id' => 'user')) !!}`

Everything works fine, my data gets displayed right and contains the name of an user as a visible value.
However when sending the form, it says "null". I already checked, when removing the classes and the  `$('#user').selectpicker();`, so using a normal select. The data gets transferred.

What could be the problem?

**Comment by caseyjhol** [comment] 2016-10-04 20:00
Duplicate of #1342.

**Closed by caseyjhol** 2016-10-04 20:00 UTC
