### ISSUE TITLE
It doesn't work on Bootstrap 4

### ISSUE THREAD

**Issue by lvxianchao** [silviomoreto/bootstrap-select#1861] opened 2017-11-22 06:37 UTC
Hi, this is a awesome project!

But it doesn't work on **Bootstrap 4.0.0-beta**， just like this:

![image](https://user-images.githubusercontent.com/22412818/33113266-8a19e472-cf92-11e7-9067-f1418a01304c.png)

**Comment by GreggOrdHume** [comment] 2017-11-22 17:40
I can second this. I fixed your issue by adding `display:block` to `.dropdown-menu.inner`.

But with `"bootstrap": "^4.0.0-beta.2"` the dropdown selects all the options at once and it throws an error.

**Cannot read property 'offsetTop' of undefined error**
```javascript
// scroll to selected option
var offset = that.$lis.eq(selectedIndex)[0].offsetTop - that.$menuInner[0].offsetTop;
offset = offset - that.$menuInner[0].offsetHeight/2 + that.sizeInfo.liHeight/2;
that.$menuInner[0].scrollTop = offset;
```

**Often the menu is out of the window**
![screen shot 2017-11-22 at 17 35 32](https://user-images.githubusercontent.com/32866970/33141618-a1919d3e-cfab-11e7-8859-5011a4400e2f.png)

**All options get selected when selecting a single option**
![screen shot 2017-11-22 at 17 38 15](https://user-images.githubusercontent.com/32866970/33141753-0ac5ce6a-cfac-11e7-85c2-4ac41eb8c719.png)

**Comment by GreggOrdHume** [comment] 2017-11-23 12:52
I see this is a duplicate of #1135

**Closed** 2017-11-23 19:59 UTC

**Comment by caseyjhol** [comment] 2018-04-19 15:41
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
