### ISSUE TITLE
How to get the previous/old value on the "change"/"changed.bs.select" event?

### ISSUE THREAD

**Issue by andrius-senulis** [silviomoreto/bootstrap-select#1404] opened 2016-06-02 10:02 UTC
Hello,

I have a problem getting the previous/old value of the select element on the change (or changed.bs.select) event. What would be the way to do it?

I don't want to use tricks like the following since I have many select elements in one page and I want to use the same event for all of them:

``` javascript
var previous;

$("select").on('focus', function () {
    previous = this.value;
}).change(function() {
    alert(previous);
    previous = this.value;
});
```

I have tried setting the data attribute with the old value to the select element but for some reason it does not get updated with the jQuery data() function.

Thank you,
Andrius

**Comment by andrius-senulis** [comment] 2016-06-02 10:12
Actually, the following trick may work out:
``` javascript
var previous_value;
$(".selectpicker").on('shown.bs.select', function(e) {
        previous_value = $(this).val();
}).change(function() {
    alert(previous_value);
    previous_value = $(this).val();
});
```

**Comment by stimko68** [comment] 2016-11-18 18:16
Is there any solution for this yet? I tried @andrius-senulis suggestion above but it's not working for me. I also have multiple select boxes which are dynamically added to the page, and I need to be able to get the old and new values.

I've also tried creating a JS function that would set the `previous` value and set that to the `onfocus` attribute of the select, like so:

```html
<select class="selectpicker" onfocus="setPreviousValue(this.value)">
    <option>1</option>
</select>
```

```javascript
var previous;

function setPreviousValue(newValue) {
    previous = newValue;
}
```

The `onfocus` attribute appears to be ignored. According to the documentation there is a reference to `oldValue` when the `changed.bs.select` event is fired but I'm not sure how to access it: https://silviomoreto.github.io/bootstrap-select/options/#events

**Comment by stimko68** [comment] 2016-11-18 18:27
Update:

So it looks like you can access the `oldValue` value like so:

```javascript
var previous;

$('.selectpicker').on('changed.bs.select', function (event, clickedIndex, newValue, oldValue) {
    previous = oldValue;
});
```

For whatever reason this still isn't working for me, but that could be an issue on my part. Maybe this will help someone else though.

**Comment by tbruyelle** [comment] 2016-12-05 22:08
Same situation here, I get only boolean values from`newValue` and `oldValue`. I thought they would contain the content of `option[value]`.

**Comment by yigitozkavci** [comment] 2016-12-08 08:09
Yes. I am also getting boolean values from `newValue` and `oldValue` parameters. Docs forward me to wrong path it seems: https://silviomoreto.github.io/bootstrap-select/options/

**Comment by Avlexz** [comment] 2017-02-20 10:26
Hi guys. As far as i debugged you can find the previous value in the outer or inner html. That being said, using jQuery I get it like that:
`$('[id$="_position_selector"].shown select').change(function() {
                var previous_val = $($(this)[0].outerHTML).val();
                console.log(previous_val);
});`

Hope this helps! ;)

**Comment by Avlexz** [comment] 2017-02-20 11:47
Hi guys. Recently I've encountered the same problem and I solved it using "shown.bs.select" event:

```
var previous_val;
$('[id$="_position_selector"].shown select').on('shown.bs.select', function() {
    previous_val = $(this).val();
}).change(function() {
    //do your action here
});
```

Hope this helps! ;)

**Comment by GreggOD** [comment] 2017-06-20 15:30
Hey guys, for knowledge: the oldValue and newValue only return true/false.

For me the issue is that the shown.bs.select event doesn't get fired. Im pretty sure its due to the project im working on having multiple inclusions of jquery and bootstrap... dont ask me why, im just working with what I have here. Any ideas? I need the old value to do a comparison.

**Comment by GreggOD** [comment] 2017-06-20 15:36
Hi guys,

As a note, the newValue and oldValues are supposed to return true/false, its the way they want it.

If you like me and show/shown events dont fire (my reason is due to jquery and bootstrap being included more than once **dont ask me, company thing)

I did this to disable selected options and re-enable them should they not be select anymore.

Great solution:
```
        $('.selectpicker').on('changed.bs.select', function (event, clickedIndex, newValue, oldValue) {
            // check the old value
            var wasSelected = $(this).attr('data-selected');
            
            if ( wasSelected != "" ){
               $('.selectpicker').not( $(this) ).find('[value="'+wasSelected+'"]').prop('disabled', false);
            }
            // disable the new value in all select pickers but this one
            $('.selectpicker').not( $(this) ).find('[value="'+$(this).val()+'"]').prop('disabled', true);
            
            // Set the new value
            $(this).attr( 'data-selected', $(this).val() );
            
            // Refresh the selectpicker to reflect updates
            $('.selectpicker').selectpicker('refresh');
        });
```

**Comment by jhonkrave** [comment] 2017-10-12 07:30
@andrius-senulis thanks!! it's working for me.

**Comment by caseyjhol** [comment] 2018-04-19 15:31
Released in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)! @andrius-senulis Please feel free to close this issue.

**Closed** 2018-04-19 15:35 UTC

**Comment by Supposer** [comment] 2019-02-22 07:55
thank you

**Comment by Lanzeca** [comment] 2021-09-29 17:08
> Actually, the following trick may work out:
> 
> ```js
> var previous_value;
> $(".selectpicker").on('shown.bs.select', function(e) {
>         previous_value = $(this).val();
> }).change(function() {
>     alert(previous_value);
>     previous_value = $(this).val();
> });
> ```
Thank you so much!

For those using Oracle APEX, this worked flawlessly for me using it with a Select List item at least on APEX 20.2.
