### ISSUE TITLE
Supporting nested optgroup's

### ISSUE THREAD

**Issue by tristanlee85** [silviomoreto/bootstrap-select#910] opened 2015-02-06 20:40 UTC
Have there been any thoughts on supporting multiple nested `optgroup`s? Assume the following:

```html
<select name="...">
   <optgroup label="Tier 1">
      <optgroup label="Level A">
         <option value="1">Row 1</option>
         <option value="1">Row 1</option>
      </optgroup>
      <optgroup label="Level B">
         <option value="3">Row 3</option>
         <option value="4">Row 4</option>
      </optgroup>
   </optgroup>
</select>
```

With how this plugin currently works, it only checks the immediate parent of the option and not potential parent**s** of type `optgroup`.

**Comment by caseyjhol** [comment] 2015-04-24 22:00
Duplicate of #180

**Closed by caseyjhol** 2015-04-24 22:00 UTC
