### ISSUE TITLE
Keyboard navigation bug

### ISSUE THREAD

**Issue by mladenko** [silviomoreto/bootstrap-select#1140] opened 2015-09-02 06:52 UTC
When i try to select options with a keyboard arrow keys, it always skip one option and moves next one( if i was on first and i press arrow down, it moves to third option not second). How to fix that?

**Comment by caseyjhol** [comment] 2015-09-02 16:36
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.

**Comment by artur-dev** [comment] 2015-09-04 11:44
I have similar problem but it's skipping 2 lines when using down arrow. Up arrows behaves normally. Will try to debug and create test case over weekend.

**Comment by acshef** [comment] 2015-09-08 22:14
http://silviomoreto.github.io/bootstrap-select/#optgroup Seems to occur whenever there are optgroups or dividers.

**Comment by artur-dev** [comment] 2015-09-15 17:33
Bingo! So it's reproducible on your examples page. Is it enough to start work?

**Comment by caseyjhol** [comment] 2015-09-29 16:57
No - the version on the examples page is very outdated, and there have been many improvements to keyboard navigation since then.

At the very least:

* Check if the issue has been fixed. Try to reproduce it using the latest master or development branch in the repository.
* Provide environment details. Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.

**Comment by acshef** [comment] 2015-09-29 17:32
Environment Details:
* Windows 7 64-bit, Windows 8.1 64-bit
* Chrome 44,45, IE10, Edge
* jQuery 1.11.3, 2.1.3
* Bootstrap 3.3.5
* Bootstrap-select 1.7.3

Here's the problem using the 1.7.3 RELEASE: http://codepen.io/anon/pen/ZbLQXO.
However, using the MASTER BRANCH: http://codepen.io/anon/pen/YyNwYv the problem appears to be fixed.
Thank you for taking the time to look at this, @caseyjhol.

**Comment by andrelgarcia** [comment] 2016-08-01 22:11
Duplicate of #1453 

I have managed to reproduce this on the latest Bootstrap-select 1.10.0 on Chrome 52 and Safari running on OSX El Capitan.

**Comment by caseyjhol** [comment] 2016-08-01 23:46
@andrelgarcia Please link me to a live example. According to @acshef, this problem has been resolved.

**Closed** 2017-07-10 21:54 UTC
