### ISSUE TITLE
last option is hidden when live search is enabled and list exceeds height of window

### ISSUE THREAD

**Issue by johnnysainz** [silviomoreto/bootstrap-select#1590] opened 2016-12-14 22:12 UTC
Able to reproduce in all browsers. When the live search box is added to the outerlist, the innerlist is pushed down and the last option is not accessible. 

Adding the following to setSize() for the fix:
`searchHeight = this.options.liveSearch ? 30 : 0 `
`'max-height': menuHeight - headerHeight - searchHeight - actionsHeight - doneButtonHeight - menuPadding.vert - searchHeight + 'px',`

![screen shot 2016-12-14 at 2 08 32 pm](https://cloud.githubusercontent.com/assets/529202/21203453/5cb5a0e6-c207-11e6-9b2e-4f2c7fd423af.png)

**Comment by birjolaxew** [comment] 2016-12-15 08:04
[Cannot reproduce.](https://jsfiddle.net/txkuujog/)

![image](https://cloud.githubusercontent.com/assets/4542461/21216158/827a657a-c2a5-11e6-95ee-359bc0051dfa.png)

**Comment by simonberger** [comment] 2016-12-16 12:27
I have this issue since a long time as well. Tried updating the plugin to the newest version and was pretty optimistic that got fixed.
But for me it still looks same as for johnnysainz (it just appears under the select box).
Tested on chrome 55. Firefox is ok btw. It would be fixed if I lower the ul dropdown-menu innerby about 12px.

**Comment by caseyjhol** [comment] 2016-12-16 16:43
Please provide an example.

**Comment by simonberger** [comment] 2016-12-30 10:54
I tried to create an example a week ago but wasn't able to build the html structure the bug appears on.
It really doesn't seem to be the clear problem I thought it is.
Also walking through all elements of my application where the bug exists and the bootstrap select element itself I can't find any attributes causing this.

If someone has more luck please create such an example. I'll try again if I have some time.

**Comment by simonberger** [comment] 2016-12-30 13:22
Ok I got a new idea and here finally is a bug-example:

http://plnkr.co/edit/0K7uegP9puwrJ7ZM4Hs7

It turned out it is the css of a template system we use. It was enough to add this to the example.
I'm still not quiet sure which style exactly it is but I guess you can find this out fast.

**Comment by simonberger** [comment] 2017-01-02 10:58
I had to find that out.
The issue comes from a height: 100% that is on .form-control. bootstrap itself does that only in some combinations.
It is a bit spooky. The following style fixes it in the demo.

`span.form-control {
      height: 34px !important;
}`

But I couldnt find the element where div, input and select have one that doesnt fix it.

**Comment by birjolaxew** [comment] 2017-01-02 13:06
[Link to offending code.](https://github.com/silviomoreto/bootstrap-select/blob/ba65054cc966da18634f14a7215840e3e24edc31/js/bootstrap-select.js#L840-L845)

The function (`liHeight`) calculates various height values by inserting a mock menu in the DOM. This mock menu isn't a perfect duplicate of the actual menu (uses `<span>` instead of `<input>` for search, as pointed out by @simonberger), so any CSS that changes the height of specifically `span`s or `input`s will break the height calculations.

**Comment by simonberger** [comment] 2017-01-02 13:29
Thanks for the additional information.
It seems to not just brake if there is special CSS for span. If you set height to 100% instead of 0px in your fiddle you have the same setup I have in real.
The result is the same error. But if the bootstrap-select calculation function uses an input tag instead of the span it most likely gonna work (assumed both use the 100% CSS height)

**Comment by cjkumaresh** [comment] 2017-01-11 10:58
Adding the below css solved the issue
`.dropdown-menu.open {
	max-height: none !important;	
}`

**Comment by simonberger** [comment] 2017-01-11 14:58
This lets the outer absolutely positioned container theoretically spread limitless.
If this would work all the expensive dimension calculation could be removed.

Did you test this suggestion?

**Comment by cjkumaresh** [comment] 2017-01-30 07:53
@simonberger : I have tested this. You're right those calculation could be removed 
[JS Fiddle](https://jsfiddle.net/cjkumaresh/s279o0mp/1/)

**Comment by caseyjhol** [comment] 2017-01-30 20:12
Setting max-height to none works if the select is the only thing on the page. Otherwise, the menu overflows the window, causing an additional unnecessary scrollbar to appear. All of the calculations are necessary. See https://jsfiddle.net/s279o0mp/2/. There's a slight performance hit using input over span, but it's pretty negligible, so I'll switch to that in the next version.

**Closed** 2017-01-30 20:17 UTC

**Comment by caseyjhol** [comment] 2017-01-30 20:30
v1.12.2 has officially been released.
