### ISSUE TITLE
Does not work with bootstrap 4 

### ISSUE THREAD

**Issue by kamranbashir** [silviomoreto/bootstrap-select#1629] opened 2017-02-07 15:31 UTC
Does any one has bootstrap 4 running version?

**Comment by huphtur** [comment] 2017-02-07 16:00
Looks like there's a PR ready for this? #1522

**Comment by caseyjhol** [comment] 2017-02-07 23:31
Duplicate of #1135. In the future, please use the search feature.

**Closed by caseyjhol** 2017-02-07 23:31 UTC

**Comment by caseyjhol** [comment] 2018-04-19 15:41
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
