### ISSUE TITLE
Select loses selection on browser navigation

### ISSUE THREAD

**Issue by ypnos-web** [silviomoreto/bootstrap-select#1296] opened 2016-02-15 18:07 UTC
In modern browsers if you navigate away from the form and back, its contents are preserved.

Testing with Chrome 48, I realized:
 * After returning to the form, the select briefly shows the correct selection before being overdrawn by boostrap-select with nothing selected (first option)
 * Even if there was a default selection set on the page, bootstrap-select will not reset to the default selection, but nothing selected.

HTML:
``` html
<select name="properties[0][value_boolean]" class="form-control "  class="selectpicker" data-style="btn-form" title="N/A" id="properties-0-value-boolean">
    <option value="-1"></option>
    <option value="1" selected="selected">Yes</option>
    <option value="0">No</option>
</select>
```

**Comment by MemoLabra** [comment] 2016-04-06 19:07
Facing same issue Chrome 49, OSX

**Comment by caseyjhol** [comment] 2016-04-07 04:58
Duplicate of #1023.

**Closed by caseyjhol** 2016-04-07 04:58 UTC
