### ISSUE TITLE
Laravel form submit - select don't pass

### ISSUE THREAD

**Issue by ilyadavydyuk** [silviomoreto/bootstrap-select#1505] opened 2016-09-09 20:56 UTC
Very simple select:
```
<form action="laravel-request" method="post">
<select name="qq[]" multiple class="selectpicker">
  <option value="1">1</option>
  <option value="2">2</option>
</select>
<button type="submit">Send</button>
```

If no _selectpicker_ class - form submit select values successfully. If _selectpicker_ is active - form send _NULL_

What am I doing wrong?
bootstrap-select last ver.
laravel 5.2

**Comment by caseyjhol** [comment] 2016-09-09 22:54
Duplicate of #1342.

**Closed by caseyjhol** 2016-09-09 22:54 UTC
