### ISSUE TITLE
HTML5 Required Attribute Does Not Show Validation Message

### ISSUE THREAD

**Issue by ddelella** [silviomoreto/bootstrap-select#1142] opened 2015-09-02 18:55 UTC
Using a standard HTML5 select tag with the required attribute produces a "fly out" validation message which reads, "You must choose an item from the list".  However, when the class selectpicker is added to a select tag the validation is performed but no message is displayed.  In the attached link below there is an example of the select with the class applied.  To show the proper action remove the class="selectpicker" attribute.

https://jsfiddle.net/ddelella/vhes5y23/5/

**Comment by caseyjhol** [comment] 2015-10-22 17:59
Closing as duplicate of #514.

**Closed by caseyjhol** 2015-10-22 17:59 UTC
