### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by clund** [silviomoreto/bootstrap-select#1666] opened 2017-03-06 16:58 UTC
While it is still early days for Bootstrap 4, making this excellent addition compatible would be very welcome.

**Comment by caseyjhol** [comment] 2017-03-07 20:36
Duplicate of #1135. Please search next time.

**Closed by caseyjhol** 2017-03-07 20:36 UTC

**Comment by infostreams** [comment] 2017-06-22 09:22
Bootstrap 4 [is 99% complete](https://github.com/twbs/bootstrap/milestones). The likelihood of major breaking changes looks pretty small at this point, so perhaps it's time to start thinking of supporting it? That it doesn't work in Bootstrap 4 *is* a dealbreaker, and so the only option people have is to fork it and apply the fixes from the comments to make it work provisionally. Perhaps you can keep a 'working draft' of Bootstrap 4 support in a separate branch? This would already be a huge improvement.

**Comment by caseyjhol** [comment] 2018-04-19 15:41
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
