### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by HamedFathi** [silviomoreto/bootstrap-select#1870] opened 2017-12-04 05:53 UTC
Please support the latest version of Bootstrap 4.
thanks

**Comment by krystyna93** [comment] 2017-12-04 09:52
@HamedFathi and others, here is a compatible version that you can use in the meantime:
https://github.com/heimrichhannot/bootstrap-select

Its the same but has been modified for compatibility, and it functions perfectly in bootstrap 4 beta. I am using this in my current project, and it all works fine.

**Comment by caseyjhol** [comment] 2017-12-04 19:29
Duplicate of #1135.

**Closed by caseyjhol** 2017-12-04 19:29 UTC

**Comment by caseyjhol** [comment] 2018-04-19 15:41
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
