### ISSUE TITLE
Checkmarks on every option

### ISSUE THREAD

**Issue by toddbruner** [silviomoreto/bootstrap-select#905] opened 2015-02-05 00:28 UTC
Given:
```html
<html>
  <head>
    <script type="text/javascript"
            src="/vast/libs/jquery-2.1.0.min.js"></script>
    <script type="text/javascript"
            src="/vast/libs/jquery.cookie.js"></script>
    <script type="text/javascript"
            src="/vast/libs/jquery.dynatable.js"></script>
    <script type="text/javascript"
            src="/vast/libs/bootstrap.min.js"></script>
    <script type="text/javascript"
            src="/vast/libs/jquery.datetimepicker.js"></script>
    <script type="text/javascript"
            src="/vast/libs/bootstrap-select.js"></script>
    <link   type="text/css"
            href="/vast/css/bootstrap.min.css"
            rel="stylesheet"
            >
    <script>
        jQuery(document).ready(
            function() {
                $('.selectpicker').selectpicker({
                    header: false,
                });
            }
        );
    </script>
  </head>
  <body>
    <h1> Test </h1>
    <select id="foo" name="foo" data-size="3" class="selectpicker">
        <option value="1">one</option>
        <option value="2">two</option>
        <option value="3">three</option>
    </select>
  </body>
</html>
````

This is what I see.

![foo](https://cloud.githubusercontent.com/assets/327826/6052685/e33dfda2-ac92-11e4-9f52-dcb238ed8ed9.jpg)

Why are the checkmarks appearing?  I've tried .deselectAll() and the checkmarks remain.
I'm using version 1.6.3.  Browser is latest Chrome on Mac OS X 10.9.

Thanks.

**Comment by Ultima2876** [comment] 2015-02-05 14:15
I used this hack to get around it:

$('.selectpicker').selectpicker({
        tickIcon: '',
    });

But yes, this is a pretty obviously broken feature (and has been in since October).

**Comment by atteeela** [comment] 2015-02-27 21:40
Same issue here.

For me however, all of my options do not show up (no scroll bars)

**Comment by caseyjhol** [comment] 2015-03-03 10:05
I can't reproduce this in 1.6.4 - can you link me to a jsFiddle?

**Comment by Deemoe** [comment] 2015-04-02 00:21
I see both of these problems in 1.6.4 too.

The $('.selectpicker').selectpicker({
tickIcon: '',
});
 trick works for me, thanks @Ultima2876 .

@atteeela  - try setting the size of your control > the number of items displayed.  I saw no items rendered when I had size: 5 and tried to render 8 items (no scroll bar), but it does render when  I changed the size: 
            $('.selectpicker').selectpicker({
                size: 100
            }); 

Hope that helps...

**Comment by caseyjhol** [comment] 2015-04-09 23:19
I would love it if somebody could link me to an example. It would make it a lot easier to troubleshoot this.

**Comment by Ultima2876** [comment] 2015-04-09 23:46
I tried to reproduce it on another site and failed - http://www.kickbackgames.com/selecttest.php. Unfortunately the site that exhibits the issue is private and I cannot link it. Maybe one of the other guys can help?

**Comment by marisbest2** [comment] 2015-05-01 03:17
I'm having this issue right now.

Here's some code from a django template
```python
    <select class="selectpicker" data-size="100px" data-live-search="true">
      {% for group in groups %}
        <option value="{{group.slug}}">{{group}}</option>
      {% endfor %}
    </select> 
```
The rendered DOM has elements that look like:
```html
<li data-original-index="1">
    <a tabindex="0" class="" data-normalized-text="<span class=&quot;text&quot;>Anime-Manga</span>"><span class="text">Anime-Manga</span>
<span class="glyphicon glyphicon-ok check-mark"></span></a></li>
```
Obviously that glyphicon shouldnt be there

**Comment by caseyjhol** [comment] 2015-05-05 16:21
`<span class="glyphicon glyphicon-ok check-mark"></span>` is always there. Its visibility is controlled via CSS. Has anybody been able to reproduce this with a reduced test case? Any chance somebody can link me to an example?

**Comment by marisbest2** [comment] 2015-05-06 01:19
I had previously been using a downloaded version of 1.6.3. Now using the CDN version and it works great.

**Comment by caseyjhol** [comment] 2015-05-06 20:10
Closing this until somebody can provide me with an example.

**Closed by caseyjhol** 2015-05-06 20:10 UTC

**Comment by 51001624** [comment] 2015-11-13 16:58
Hello, everybody !
I am trying to show the content of the missing text in selectpicker (because the content of the option was very long), i used tooltip with title but it didn't work, what should i do, thanks !

**Comment by caseyjhol** [comment] 2015-11-13 17:49
@51001624 see http://stackoverflow.com/questions/31270151/silviomoreto-bootstrap-select-tooltip-on-options/31525497#31525497

**Comment by 51001624** [comment] 2015-11-15 15:33
Thanks caseyjhol, I will ask you again if i can't figure out the solution for it !

**Comment by 51001624** [comment] 2015-11-15 15:36
ah, what do you mean about li, instead of using select tag i use ul and li with the selectpicker class?

**Comment by jiayu427** [comment] 2017-04-06 21:43
I had the same issue, and then I realized I only imported the bootstrap-select.js file, after importing the bootstrap-select.css file, the checkmarks are gone.
