### ISSUE TITLE
Support for contextual classes

### ISSUE THREAD

**Issue by LoLFactor** [silviomoreto/bootstrap-select#815] opened 2014-11-26 23:01 UTC
You should add support for Bootstrap form-group contextual classes.

For those of you looking for a quick fix to the same problem, here's one in plain CSS:

```
.form-group.has-success .bootstrap-select .btn.dropdown-toggle {
    border-color: #3C763D;
}
```
Now just replace the `.has-success` part with any other contextual class and replace the color value accordingly.

**Comment by caseyjhol** [comment] 2015-05-28 00:21
Duplicate of #569.

**Closed by caseyjhol** 2015-05-28 00:21 UTC
