### ISSUE TITLE
Feature Request: Select All Options in a Group By Selecting Optgroup Label

### ISSUE THREAD

**Issue by meetmagdalene** [silviomoreto/bootstrap-select#997] opened 2015-04-16 15:04 UTC
I don't know if this is update worthy, but I'm looking to add this capability to a selectpicker I'm making which is being populated by php.

example:
```
<select class="selectpicker">
    <optgroup label="CustomerGroup1">
      <option>Customer 1.1</option>
      <option>Customer 1.2</option>
      <option>Customer 1.3</option>
    </optgroup>
    <optgroup label="CustomerGroup2">
      <option>Customer 2.1</option>
      <option>Customer 2.2</option>
      <option>Customer 2.3</option>
    </optgroup>
  </select>
```

I don't know enough JS to make something on the fly myself or I'm wondering if this could be a feature added if more people would find this useful, but I want the user to be able to click on the label (like they are selecting it) and the whole group be toggled as selected.

**Comment by caseyjhol** [comment] 2015-04-24 22:01
Duplicate of #737

**Closed by caseyjhol** 2015-04-24 22:01 UTC
