### ISSUE TITLE
when I set maxOptionsText is String(not function), Just show the first letter of my string

### ISSUE THREAD

**Issue by lovewuyong** [silviomoreto/bootstrap-select#1352] opened 2016-04-06 10:26 UTC
in line 1127
var maxOptionsArr = (typeof that.options.maxOptionsText === 'function') ?
                          that.options.maxOptionsText(maxOptions, maxOptionsGrp) : that.options.maxOptionsText,
                      maxTxt = maxOptionsArr[0].replace('{n}', maxOptions),
I think the maxTxt need to set in different condition of function and String.

**Comment by caseyjhol** [comment] 2016-04-06 18:09
Duplicate of #1300.

**Closed by caseyjhol** 2016-04-06 18:09 UTC
