### ISSUE TITLE
Deny native dropdown on mobile devices

### ISSUE THREAD

**Issue by MarcelDoesCode** [silviomoreto/bootstrap-select#1450] opened 2016-07-24 15:12 UTC
I have the problem that bootstrap select fields do not work on mobile devices. The native mobile browser dropdown is opening which causes that the change event, that is triggered on desktop, isn't triggered on mobile.

**Comment by caseyjhol** [comment] 2016-08-06 19:16
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.

**Comment by caseyjhol** [comment] 2016-08-16 18:31
Duplicate of #1465?

**Closed by caseyjhol** 2016-08-16 18:31 UTC
