### ISSUE TITLE
[FEATURE REQUEST] Select All within an Optgroup 

### ISSUE THREAD

**Issue by Flaque** [silviomoreto/bootstrap-select#1468] opened 2016-08-16 21:56 UTC
I would love to see the ability to click on a header of an optgroup and have it select or deselect all it's members. 

It could be added the same way search box's are: 

```
<select class="selectpicker" 
            data-live-search="true" 
            data-select-header="true"
            multiple
            title="Select a Country">
```

Which would then add the functionality to click on the header to select all it's members like so: 

![alt text](http://i.imgur.com/qpDTCt6.png "Example Picture didn't load :( ")

**Comment by caseyjhol** [comment] 2016-08-16 22:01
Duplicate of #737.

**Closed by caseyjhol** 2016-08-16 22:01 UTC
