### ISSUE TITLE
Problem using attribute required

### ISSUE THREAD

**Issue by repher** [silviomoreto/bootstrap-select#1095] opened 2015-07-09 21:22 UTC
Hello!

I'm working with cakephp and therefore getting on all reuired input field the attribute "required" set. This does not work with bootstrap-select because it's hidden and therefore the user doesn't get any feedback.

Original:
```html
<select name="somename" required="required" id="someid" >
    ...
</select>
```

Error message in Chrome:
`An invalid form control with name='membership[0][year]' is not focusable.`

The `required` attribute gets added by several framworks for all required fields. For example [CakePHP](http://cakephp.org).

A possible solution would be to remove all `required` attributes on selects that get hidden by `bootstrap-select`. Since there should always be some server side validation, this would not hurt anybody.

Bernhard

**Comment by caseyjhol** [comment] 2015-07-09 21:53
Duplicate of #514.

**Closed by caseyjhol** 2015-07-09 21:53 UTC
