### ISSUE TITLE
Prevent autofocus on search field for mobile users

### ISSUE THREAD

**Issue by GeeZuZz** [silviomoreto/bootstrap-select#941] opened 2015-02-24 16:38 UTC
The select lists doesn't work vert well on mobile phones when used with the search/filter option.
Because whenever the user tap on the list to select an option, the keyboard will show up and cover half of the screen, making it hard to see and scroll through the options.

Is it possible to prevent the keyboard from showing up unless the search field is selected?

**Comment by mewsoft** [comment] 2015-02-24 21:37
Yes this what I asked before https://github.com/silviomoreto/bootstrap-select/issues/912

**Comment by caseyjhol** [comment] 2015-05-08 16:20
Duplicate of #912.

**Closed by caseyjhol** 2015-05-08 16:20 UTC
